fix: Proper initialization of `bthome_measurement_record_t`
* Newer compilers are more strict about the initialization of structs,
  so we need to initialize the `is_value` field of `bthome_measurement_record_t`
  to avoid an error:

  ```
  src/esphome/components/bthome_receiver_base/bthome_receiver_base_hub.cpp:130:55:
    error: either all initializer clauses should be designated or none of them should be
  130 |               bthome_measurement_record_t data{false, .d = {.event = event_data}};
      |                                                       ^
src/esphome/components/bthome_receiver_base/bthome_receiver_base_hub.cpp:139:54:
    error: either all initializer clauses should be designated or none of them should be
  139 |               bthome_measurement_record_t data{true, .d = {.value = value_data}};
  ```